name: ci

on:
  push:
    branches:
      - 'feature/release_image'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          image_name: ghcr.io/schueco-japan/clamscan-download-defs-lambda
