name: ci

on:
  push:
    branches:
      - 'feature/release_image'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
         - download-defs
         - scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Push
        uses: ./.github/actions/build_and_push
        with:
          image_name: ${{matrix.directory}}
